Repository SOPT-all/36-COLLABORATION-WEB-DAISOMALL, pull requests merged in 2025-05, with the labels that each got.

#4 [INIT] Issue 템플릿, PR 템플릿 생성 #3
  .github/ISSUE_TEMPLATE/issue-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 지수 🌏, Init 🌱

#10 [INIT] Prettier · ESLint 설정 #9
  .prettierrc
  eslint.config.js
  package.json
  yarn.lock
Labels: 채은 🪽, Init 🌱

#8 [INIT] 프로젝트 절대 경로 설정 #7
  package.json
  src/pages/.gitkeep
  src/types/.gitkeep
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 지수 🌏, Init 🌱

#6 [INIT] SVG · Theme · Global Style 구성
  .pnp.cjs
  .pnp.loader.mjs
  .yarn/install-state.gz
  custom.d.ts
  package.json
  src/App.tsx
  src/custom-modules.d.ts
  src/main.tsx
  src/styles/emotion.d.ts
  src/styles/fonts/DAISOA/Daisofont.woff
  src/styles/fonts/Pretendard/Pretendard-Bold.woff
  src/styles/fonts/Pretendard/Pretendard-Medium.woff
  src/styles/fonts/Pretendard/Pretendard-Regular.woff
  src/styles/fonts/Pretendard/Pretendard-SemiBold.woff
  src/styles/fonts/fonts.css
  src/styles/global.ts
  src/styles/reset.ts
  src/styles/theme.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: 경호 🧑🏻‍🌾, Init 🌱

#15 [FIX] 초기세팅 에러 해결 #13
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .yarn/install-state.gz
  .yarnrc.yml
  commitlint.config.js
  custom.d.ts
  index.html
  package.json
  pnpm-lock.yaml
  public/logo.png
  public/svgs/react.svg
  src/App.tsx
  src/assets/svgs/React.tsx
  src/assets/svgs/index.ts
  src/custom-modules.d.ts
  src/main.tsx
  src/styles/emotion.d.ts
  src/styles/fonts/.gitkeep
  src/styles/fonts/fonts.css
  src/styles/global.ts
  src/styles/reset.ts
  src/styles/theme.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 채은 🪽, 👾 Fix

#28 [FEAT] Header 네비게이션 컴포넌트 구현 #17
  src/components/HeaderNav/HeaderNav.style.ts
  src/components/HeaderNav/HeaderNav.tsx
Labels: 🪽 채은, ✨ Feature

#30 [FEAT] Bottom 네비게이션 컴포넌트 구현 #18
  public/svgs/_category-icon-new.svg
  public/svgs/home-icon-active.svg
  public/svgs/home-icon.svg
  public/svgs/mypage-icon.svg
  public/svgs/offline-search-active.svg
  public/svgs/offline-search-large.svg
  public/svgs/offline-search.svg
  public/svgs/recent-icon.svg
  src/assets/svgs/CategoryIconNew.tsx
  src/assets/svgs/HomeIcon.tsx
  src/assets/svgs/HomeIconActive.tsx
  src/assets/svgs/MypageIcon.tsx
  src/assets/svgs/OfflineSearch.tsx
  src/assets/svgs/OfflineSearchActive.tsx
  src/assets/svgs/OfflineSearchLarge.tsx
  src/assets/svgs/RecentIcon.tsx
  src/assets/svgs/index.ts
  src/components/BottomNav/BottomNav.style.ts
  src/components/BottomNav/BottomNav.tsx
  src/styles/global.ts
Labels: 🪽 채은, ✨ Feature

#27 [FEAT] SearchBar 컴포넌트 구현 #19
  public/svgs/barcode-icon.svg
  public/svgs/cancel-icon.svg
  src/assets/svgs/BarcodeIcon.tsx
  src/assets/svgs/CancelIcon.tsx
  src/assets/svgs/index.ts
  src/components/HeaderNav/HeaderNav.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/searchBar.style.ts
Labels: 🪼 소은, ✨ Feature

#23 [FEAT] 플로팅 버튼 컴포넌트 구현 #22
  .yarn/install-state.gz
  public/svgs/chatbot-icon.svg
  public/svgs/floatingup-icon.svg
  src/assets/svgs/ChatbotIcon.tsx
  src/assets/svgs/FloatingUpIcon.tsx
  src/assets/svgs/index.ts
  src/components/buttons/floatingButtons/ChatbotButton.style.ts
  src/components/buttons/floatingButtons/ChatbotButton.tsx
  src/components/buttons/floatingButtons/FloatingUpButton.style.ts
  src/components/buttons/floatingButtons/FloatingUpButton.tsx
  src/styles/theme.ts
Labels: 🌏 지수, ✨ Feature

#25 [FEAT] 아코디언 버튼 컴포넌트 구현 #24
  public/svgs/smallarrowdown-icon.svg
  public/svgs/smallarrowup-icon.svg
  src/assets/svgs/SmallArrowDownIcon.tsx
  src/assets/svgs/SmallArrowUpIcon.tsx
  src/assets/svgs/index.ts
  src/components/buttons/accordion/AccordionButton.style.ts
  src/components/buttons/accordion/AccordionButton.tsx
  src/components/common/divider/Divider.tsx
Labels: 🌏 지수, ✨ Feature

#32 [FEAT] 내비게이션 버튼 컴포넌트 구현 #31
  package.json
  public/svgs/smallarrowright-icon.svg
  src/App.tsx
  src/assets/svgs/SmallArrowRightIcon.tsx
  src/assets/svgs/index.ts
  src/components/buttons/navigationButton/NavigationButton.style.ts
  src/components/buttons/navigationButton/NavigationButton.tsx
  yarn.lock
Labels: 🌏 지수, ✨ Feature

#42 [FEAT] SectionTitle 컴포넌트 구현 #41
  .yarn/install-state.gz
  src/App.tsx
  src/assets/svgs/ChatbotIcon.tsx
  src/assets/svgs/FloatingUpIcon.tsx
  src/assets/svgs/SmallArrowDownIcon.tsx
  src/assets/svgs/SmallArrowRightIcon.tsx
  src/assets/svgs/SmallArrowUpIcon.tsx
  src/assets/svgs/index.ts
  src/components/buttons/accordion/AccordionButton.style.ts
  src/components/buttons/accordion/AccordionButton.tsx
  src/components/buttons/floatingButtons/ChatbotButton.style.ts
  src/components/buttons/floatingButtons/ChatbotButton.tsx
  src/components/buttons/floatingButtons/FloatingUpButton.style.ts
  src/components/buttons/floatingButtons/FloatingUpButton.tsx
  src/components/buttons/navigationButton/NavigationButton.style.ts
  src/components/buttons/navigationButton/NavigationButton.tsx
  src/components/common/SectionTitle/SectionTitle.style.ts
  src/components/common/SectionTitle/SectionTitle.tsx
  src/components/common/divider/Divider.tsx
Labels: 🪼 소은, ✨ Feature

#29 [FEAT] 더 보기 버튼 컴포넌트 구현 #26
  .vite/deps/_metadata.json
  .vite/deps/package.json
  src/components/buttons/floatingButtons/FloatingUpButton.style.ts
  src/components/buttons/viewMoreButton/ViewMoreButton.style.ts
  src/components/buttons/viewMoreButton/ViewMoreButton.tsx
  src/styles/theme.ts
Labels: 🌏 지수, ✨ Feature

#47 [FIX] 폰트 줄 높이 수정 #46
  src/styles/theme.ts
Labels: 🧑🏻‍🌾 경호, 🐛 Fix

#43 [FEAT] 상품 태그 컴포넌트 구현 #12
  public/svgs/star-icon-white.svg
  src/App.tsx
  src/assets/svgs/StarIconWhite.tsx
  src/assets/svgs/index.ts
  src/components/Tag/ProductTag.style.ts
  src/components/Tag/ProductTag.tsx
  src/components/Tag/tagData.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#35 [FEAT] 매장 검색바 컴포넌트 구현 #34
  public/svgs/location-icon.svg
  src/App.tsx
  src/assets/svgs/LocationIcon.tsx
  src/assets/svgs/index.ts
  src/components/StoreSearchBar/StoreSearchBar.style.ts
  src/components/StoreSearchBar/StoreSearchBar.tsx
  src/components/Tag/ProductTag.style.ts
  src/components/Tag/ProductTag.tsx
  src/components/Tag/tagData.tsx
  src/components/buttons/viewMoreButton/ViewMoreButton.style.ts
  src/components/buttons/viewMoreButton/ViewMoreButton.tsx
Labels: 🪼 소은, ✨ Feature

#38 [FEAT] 매장(location-card) 및 영업 상태 컴포넌트 구현 #36
  public/svgs/arrow-right-icon.svg
  public/svgs/like-icon.svg
  src/assets/svgs/ArrowRightIcon.tsx
  src/assets/svgs/LikeIcon.tsx
  src/assets/svgs/index.ts
  src/components/LocationCard/LocationCard.style.ts
  src/components/LocationCard/LocationCard.tsx
  src/components/LocationCard/LocationTag.tsx
  src/components/LocationCard/StoreActionButton/StoreActionButton.tsx
  src/components/LocationCard/StoreStatus/StoreStatus.style.ts
  src/components/LocationCard/StoreStatus/StoreStatus.tsx
Labels: 🪼 소은, ✨ Feature

#45 [FEAT] 배너 캐러셀 UI 구현 #14
  package.json
  public/banner1.png
  public/banner2.png
  public/banner3.png
  public/banner4.png
  public/banner5.png
  public/banner6.png
  src/App.tsx
  src/components/ImageCarousel/ImageCarousel.style.ts
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/OrderIndicator/OrderIndicator.style.ts
  src/components/OrderIndicator/OrderIndicator.tsx
  yarn.lock
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#44 [FEAT] 매장 탭 필터 UI 컴포넌트 구현 #11
  public/svgs/x-icon.svg
  src/App.tsx
  src/assets/svgs/XIcon.tsx
  src/assets/svgs/index.ts
  src/components/tabs/FilterTabs.style.ts
  src/components/tabs/FilterTabs.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#66 [SETTING] Router 초기 설정 #56
  .yarn/install-state.gz
  package.json
  src/App.tsx
  src/pages/.gitkeep
  src/pages/HomePage/HomePage.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/StoreSearchPage/StoreSearchPage.tsx
  src/routes/Router.tsx
  src/routes/pageRoutes.tsx
  src/routes/routePath.ts
  src/types/.gitkeep
  src/types/routeType.ts
  tsconfig.app.json
  yarn.lock
Labels: 🧑🏻‍🌾 경호, 🪽 채은, ⚙️ Setting

#33 [FEAT] Product Card 컴포넌트 구현 #20
  public/svgs/bookmark-icon.svg
  public/svgs/deliverybox-icon.svg
  public/svgs/multiple-icon.svg
  public/svgs/sns-icon.svg
  src/assets/svgs/BookmarkIcon.tsx
  src/assets/svgs/BoxIcon.tsx
  src/assets/svgs/MultipleIcon.tsx
  src/assets/svgs/SnsIcon.tsx
  src/assets/svgs/index.ts
  src/components/ImageCarousel/ImageCarousel.style.ts
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/OrderIndicator/OrderIndicator.tsx
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.style.ts
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.tsx
  src/components/ProductCard/ProductCardVertical/ProductCardVertical.style.ts
  src/components/ProductCard/ProductCardVertical/ProductCardVertical.tsx
  src/components/ProductCard/ProductTag.tsx
  src/components/ProductCard/TodayCard/TodayCard.style.ts
  src/components/ProductCard/TodayCard/TodayCard.tsx
  src/components/tabs/FilterTabs.style.ts
  src/components/tabs/FilterTabs.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/StoreSearchPage/StoreSearchPage.tsx
  src/routes/routePath.ts
Labels: 🪼 소은, ✨ Feature

#64 [FEAT] 홈 페이지 캐러셀 섹션 구현 #54
  public/home-carousel-1.png
  public/home-carousel-2.png
  public/home-carousel-3.png
  src/App.tsx
  src/components/homeCarousel/HomeCarousel.style.ts
  src/components/homeCarousel/HomeCarousel.tsx
Labels: 🌏 지수, ✨ Feature

#81 [FEAT] 상세페이지 네비게이션 바 구현 #62
  src/main.tsx
  src/pages/ProductDetailPage/NavBar/NavBar.style.ts
  src/pages/ProductDetailPage/NavBar/NavBar.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#72 [FEAT] 상세페이지 제품&브랜드 정보 컴포넌트 #57
  public/svgs/shareIcon.svg
  public/svgs/starIcon.svg
  src/App.tsx
  src/assets/svgs/ProductPageInfo/ShareIcon.tsx
  src/assets/svgs/ProductPageInfo/StarIcon.tsx
  src/assets/svgs/index.ts
  src/pages/ProductPage/components/ProductHeader.style.ts
  src/pages/ProductPage/components/ProductHeader.tsx
  src/pages/ProductPage/components/ProductPageInfo.style.ts
  src/pages/ProductPage/components/ProductPageInfo.tsx
  src/pages/ProductPage/components/Rating.style.ts
  src/pages/ProductPage/components/Rating.tsx
  src/styles/global.ts
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#76 [FEAT] 상세페이지 배송 & 픽업 컴포넌트 UI 구현
  public/svgs/BetaMark.svg
  public/svgs/PickupTomorrow.svg
  public/svgs/QuestionCircle.svg
  public/svgs/boxIcon.svg
  public/svgs/deliveryIconCycle.svg
  public/svgs/deliveryIconTruck.svg
  public/svgs/deliverybox-icon.svg
  public/svgs/storeIcon.svg
  src/assets/svgs/BetaMark.tsx
  src/assets/svgs/BoxIcon.tsx
  src/assets/svgs/DeliveryIconCycle.tsx
  src/assets/svgs/DeliveryIconTruck.tsx
  src/assets/svgs/PickupTomorrow.tsx
  src/assets/svgs/QuestionCircle.tsx
  src/assets/svgs/StoreIcon.tsx
  src/assets/svgs/index.ts
  src/components/buttons/navigationButton/NavigationButton.style.ts
  src/pages/ProductDetailPage/PickupInfo/MethodListSection.style.ts
  src/pages/ProductDetailPage/PickupInfo/MethodListSection.tsx
  src/pages/ProductDetailPage/PickupInfo/PickupDetailsSection.style.ts
  src/pages/ProductDetailPage/PickupInfo/PickupDetailsSection.tsx
  src/pages/ProductDetailPage/PickupInfo/PickupInfo.style.ts
  src/pages/ProductDetailPage/PickupInfo/PickupInfo.tsx
  src/pages/ProductDetailPage/PickupInfo/PickupStoreSection.style.ts
  src/pages/ProductDetailPage/PickupInfo/PickupStoreSection.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#77 [FEAT] 상세페이지 혜택 안내 섹션 컴포넌트 구현 #61
  src/assets/svgs/DeliveryboxIcon.tsx
  src/assets/svgs/index.ts
  src/pages/ProductDetailPage/PerkInfo/InfoColumn/InfoColumn.style.ts
  src/pages/ProductDetailPage/PerkInfo/InfoColumn/InfoColumn.tsx
  src/pages/ProductDetailPage/PerkInfo/LabelColumn/LabelColumn.style.ts
  src/pages/ProductDetailPage/PerkInfo/LabelColumn/LabelColumn.tsx
  src/pages/ProductDetailPage/PerkInfo/PerkInfo.style.ts
  src/pages/ProductDetailPage/PerkInfo/PerkInfo.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#82 [FEAT] 상세페이지 브랜드 정보 섹션 컴포넌트 구현 #63
  src/App.tsx
  src/pages/ProductDetailPage/BrandInfo/BrandInfo.style.ts
  src/pages/ProductDetailPage/BrandInfo/BrandInfo.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: 🧑🏻‍🌾 경호, ✨ Feature

#78 [FEAT] 매장 상품 찾기 - 지금 많이 찾는 상품 섹션 구현 #67
  .yarn/install-state.gz
  src/apis/search/popular.ts
  src/components/BottomNav/BottomNav.style.ts
  src/components/BottomNav/BottomNav.tsx
  src/components/Header/Header.tsx
  src/components/ProductCard/ProductCardRanking/LazyImage.tsx
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.style.ts
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/pagination/Pagination.style.ts
  src/components/pagination/Pagination.tsx
  src/components/storeSearch/StoreSearchStates.tsx
  src/hooks/queries/usePopularProducts.ts
  src/hooks/usePaginationWithPreload.ts
  src/hooks/useSwipeNavigation.ts
  src/pages/StoreSearchPage/PopularProductsSection.style.ts
  src/pages/StoreSearchPage/PopularProductsSection.tsx
  src/pages/StoreSearchPage/StoreSearchPage.style.ts
  src/pages/StoreSearchPage/StoreSearchPage.tsx
  src/types/popularProducts.ts
  src/utils/constants/api/api.ts
Labels: 🌏 지수, ✨ Feature

#86 [FEAT] 매장 상품 찾기 - 상품 검색 섹션 구현 및 API 연동 #83
  .yarn/install-state.gz
  public/svgs/caution2-icon.svg
  public/svgs/noresult-icon.svg
  src/apis/search/.gitkeep
  src/apis/search/product.ts
  src/assets/svgs/Caution2Icon.tsx
  src/assets/svgs/NoResultIcon.tsx
  src/assets/svgs/index.ts
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.style.ts
  src/components/ProductCard/ProductCardRanking/ProductCardRanking.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/searchEmptyResult/SearchEmptyResult.style.ts
  src/components/searchEmptyResult/SearchEmptyResult.tsx
  src/components/searchResultTitle/SearchResultTitle.style.ts
  src/components/searchResultTitle/SearchResultTitle.tsx
  src/hooks/queries/useProductSortOptions.ts
  src/hooks/queries/useSearchProducts.ts
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/StoreSearchPage/PopularProductsSection.tsx
  src/pages/StoreSearchPage/SearchProductsSection.style.ts
  src/pages/StoreSearchPage/SearchProductsSection.tsx
  src/pages/StoreSearchPage/StoreSearchPage.tsx
  src/styles/global.ts
  src/types/apiResponseType.ts
  src/utils/constants/api/api.ts
Labels: 🌏 지수, ✨ Feature

#84 [FEAT] 상세페이지 하단 퍼블리싱 #68
  .yarn/install-state.gz
  public/svgs/contact-icon.svg
  public/svgs/menu-icon.svg
  public/svgs/star-icon-gray.svg
  public/svgs/star-icon-red.svg
  public/svgs/thumb-up-icon.svg
  src/assets/pngs/BottomCarousel1.png
  src/assets/pngs/BottomCarousel2.png
  src/assets/pngs/TodayImg1.png
  src/assets/pngs/TodayImg2.png
  src/assets/pngs/TodayImg3.png
  src/assets/pngs/TodayImgProfile1.png
  src/assets/pngs/TodayImgProfile2.png
  src/assets/pngs/TodayImgProfile3.png
  src/assets/svgs/ContactIcon.tsx
  src/assets/svgs/MenuIcon.tsx
  src/assets/svgs/ShareIcon.tsx
  src/assets/svgs/StarIcon.tsx
  src/assets/svgs/StarIconGray.tsx
  src/assets/svgs/StarIconRed.tsx
  src/assets/svgs/ThumbUpIcon.tsx
  src/assets/svgs/index.ts
  src/components/ProductCard/TodayCard/TodayCard.style.ts
  src/components/ProductCard/TodayCard/TodayCard.tsx
  src/components/buttons/accordion/AccordionButton.style.ts
  src/components/buttons/accordion/AccordionButton.tsx
  src/components/common/divider/Divider.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductDetailPage/components/Accordion/Accordion.style.ts
  src/pages/ProductDetailPage/components/Accordion/Accordion.tsx
  src/pages/ProductDetailPage/components/BuyBar/BuyBar.style.ts
  src/pages/ProductDetailPage/components/BuyBar/BuyBar.tsx
  src/pages/ProductDetailPage/components/Carousel/BottomCarousel.tsx
  src/pages/ProductDetailPage/components/Review/Comment.style.ts
  src/pages/ProductDetailPage/components/Review/Comment.tsx
  src/pages/ProductDetailPage/components/Review/Keywords.style.ts
  src/pages/ProductDetailPage/components/Review/Keywords.tsx
  src/pages/ProductDetailPage/components/Review/PhotoScrollList.style.ts
  src/pages/ProductDetailPage/components/Review/PhotoScrollList.tsx
  src/pages/ProductDetailPage/components/Review/RenderStars.style.ts
  src/pages/ProductDetailPage/components/Review/RenderStars.tsx
  src/pages/ProductDetailPage/components/Review/Review.style.ts
  src/pages/ProductDetailPage/components/Review/Review.tsx
  src/pages/ProductDetailPage/components/TodayDiscovery/TodayDiscovery.style.ts
  src/pages/ProductDetailPage/components/TodayDiscovery/TodayDiscovery.tsx
  src/pages/ProductDetailPage/productDetailBottom.tsx
  src/routes/pageRoutes.tsx
  src/routes/routePath.ts
Labels: 🪽 채은, ✨ Feature

#93 [FEAT] 매장 상품 찾기 페이지 컴포넌트 연결 흐름 구현 #89
  src/components/BottomNav/BottomNav.style.ts
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/HeaderNav/HeaderNav.style.ts
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/tabs/FilterTabs.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/StoreSearchPage/PopularProductsSection.tsx
  src/pages/StoreSearchPage/SearchProductsSection.tsx
  src/pages/StoreSearchPage/StoreNameSearchSection/StoreNameSearchSection.tsx
  src/pages/StoreSearchPage/StoreSearchPage.tsx
Labels: 🌏 지수, ✨ Feature
